### ISSUE TITLE
不支持设置 提交问卷后跳转到指定URL吗？

### ISSUE THREAD

**Issue by ZhiboWong** [shanghaobo/wjcat-release#42]
顺便问一下，https://www.wjcat.com/home 注册的账号数据能保留多久？

**Comment by shanghaobo** [comment]
暂不支持，后续版本可以考虑增加此功能

**Comment by shanghaobo** [comment]
> 顺便问一下，https://www.wjcat.com/home 注册的账号数据能保留多久？

正常后台是不会主动清数据的
